[DEFAULT]
upstream-branch = upstream/latest
debian-branch = debian/latest
upstream-tag = %(version)s
pristine-tar = False
pristine-tar-commit = False

[buildpackage]
sign-tags = False
export-dir = ../build-area

[dch]
auto = True
