#!/bin/sh
QMAILDIR=$(getent passwd qmaild | cut -d: -f6)
QMAILDUID=$(id -u vpopmail)
NOFILESGID=$(id -g vpopmail)
MAXSMTPD=$(cat "$QMAILDIR/control/concurrencyincoming")
SOFTLIMIT=$(cat "$QMAILDIR/control/softlimit")
LOCAL=$(head -1 "$QMAILDIR/control/me")
TCPRULES_DIR="$QMAILDIR/control"

# Require authentication on submission
export SMTPAUTH="!"
export SMTPD_GREETDELAY=3
export DROP_PRE_GREET=1
export CHKUSER_START=ALWAYS
export FORCEAUTHMAILFROM=1

if [ -x "$QMAILDIR/bin/rcptcheck-overlimit" ]; then
    export RCPTCHECK="$QMAILDIR/bin/rcptcheck-overlimit"
    export RCPTCHECKRELAYCLIENT=1
fi

exec /usr/bin/softlimit -m "$SOFTLIMIT" \
    /usr/bin/tcpserver -v -R -l "$LOCAL" \
    -x "${TCPRULES_DIR}/tcp.submission.cdb" -c "$MAXSMTPD" \
    -u "$QMAILDUID" -g "$NOFILESGID" 0 587 \
    "$QMAILDIR/bin/qmail-smtpd" \
    /home/vpopmail/bin/vchkpw /bin/true 2>&1
